xacro:
  include: "$(find arena_robots)/components/camera/vln_rgbd/vln_rgbd.urdf.xacro"
  macro: vln_rgbd
  attach:
    name: "${prefix}${mount}"
    parent_link: "${prefix}${parent}"
    sensor: "${mount}"
    topic: "${topic:-vln_camera}"
    height: "${height:-0.9815}"
  args:
    height: 0.9815
sensor:
  gz:
    - name: "${name:-vln_camera}_image"
      type: image
      topic: "${topic:-vln_camera}/image"
      frame: "${prefix}${mount}_rgb_camera_frame"
      sensor: "${mount}_rgb_camera"
    - name: "${name:-vln_camera}_info"
      type: camera_info
      topic: "${topic:-vln_camera}/camera_info"
      frame: "${prefix}${mount}_rgb_camera_frame"
      sensor: "${mount}_rgb_camera"
    - name: "${name:-vln_camera}_depth"
      type: depth
      topic: "${topic:-vln_camera}/depth_image"
      frame: "${prefix}${mount}_depth_camera_frame"
      sensor: "${mount}_depth_camera"
power:
  static_power_w: 2.0
