xacro:
  include: "$(find arena_robots)/components/camera/d435_depth/d435_depth.urdf.xacro"
  macro: d435_depth
  attach:
    name: "${camera:-${mount}}"
    parent_link: "${prefix}${parent}"
    frame: "${prefix}${mount}"
    topic: "${topic:-${mount}}"
  args: {}
sensor:
  gz:
    - name: "${name:-${mount}}_info"
      type: camera_info
      topic: "${topic:-${mount}}/camera_info"
      frame: "${prefix}${camera:-${mount}}_link"
      sensor: "${camera:-${mount}}"
    - name: "${name:-${mount}}_depth"
      type: depth
      topic: "${topic:-${mount}}/depth_image"
      frame: "${prefix}${camera:-${mount}}_link"
      sensor: "${camera:-${mount}}"
    - name: "${name:-${mount}}_points"
      type: pointcloud
      topic: "${topic:-${mount}}/depth_image/points"
      frame: "${prefix}${camera:-${mount}}_link"
      sensor: "${camera:-${mount}}"
power:
  static_power_w: 2.0
